import json
import os
from typing import Dict, Union, List, Any

def export_weekly_plan_to_json(weekly_plan: Dict[str, Union[str, Dict]], filename: str = "weekly_plan.json"):
    """
    Exports the weekly training plan to a JSON file.
    :param weekly_plan: The full weekly plan dictionary generated by the planner.
    :param filename: Filename for the JSON export.
    """
    try:
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(weekly_plan, f, indent=2, ensure_ascii=False)
        print(f"✅ Weekly plan successfully exported to '{filename}'")
    except Exception as e:
        print(f"❌ Failed to export weekly plan: {e}")

def export_json(data: Any, filename: str):
    """
    Exports data to a JSON file in the output/ directory.
    :param data: The data to export (serializable to JSON).
    :param filename: The filename to use (should end with .json).
    """
    os.makedirs("output", exist_ok=True)
    path = os.path.join("output", filename)
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"✅ Data successfully exported to '{path}'")
    except Exception as e:
        print(f"❌ Failed to export data: {e}")


